In [1]:
import numpy as np

In [20]:
A = np.array([[1,1,1],
              [1,1,0],
              [0,1,1],
              [1,0,0],
              [0,0,1]], dtype = np.float)
b = np.array([[89],
              [67],
              [53],
              [35],
              [20]], dtype = np.float)
A = np.matrix([[1,1,1],
              [1,1,0],
              [0,1,1],
              [1,0,0],
              [0,0,1]], dtype = np.float)
b = np.matrix([[89],
              [67],
              [53],
              [35],
              [20]], dtype = np.float)
X = np.zeros((3,1), dtype = np.float)

In [21]:
A.T

matrix([[ 1.,  1.,  0.,  1.,  0.],
        [ 1.,  1.,  1.,  0.,  0.],
        [ 1.,  0.,  1.,  0.,  1.]])

In [22]:
np.dot(A.T,A)

matrix([[ 3.,  2.,  1.],
        [ 2.,  3.,  2.],
        [ 1.,  2.,  3.]])

In [23]:
np.linalg.det(np.dot(A.T,A))

7.9999999999999982

In [24]:
np.linalg.inv(np.dot(A.T,A)) * np.linalg.det(np.dot(A.T,A))

matrix([[ 5., -4.,  1.],
        [-4.,  8., -4.],
        [ 1., -4.,  5.]])

In [25]:
np.linalg.inv(np.dot(A.T,A))

matrix([[ 0.625, -0.5  ,  0.125],
        [-0.5  ,  1.   , -0.5  ],
        [ 0.125, -0.5  ,  0.625]])

$(A.T * A)^(-1)$*A.T

In [26]:
np.dot(np.linalg.inv(np.dot(A.T,A)), A.T)

matrix([[  2.50000000e-01,   1.25000000e-01,  -3.75000000e-01,
           6.25000000e-01,   1.25000000e-01],
        [  1.11022302e-16,   5.00000000e-01,   5.00000000e-01,
          -5.00000000e-01,  -5.00000000e-01],
        [  2.50000000e-01,  -3.75000000e-01,   1.25000000e-01,
           1.25000000e-01,   6.25000000e-01]])

In [27]:
X_ls= np.dot(np.dot(np.linalg.inv(np.dot(A.T,A)), A.T), b) #alpha
print "X_ls\n", X_ls

X_ls
[[ 35.125]
 [ 32.5  ]
 [ 20.625]]


In [28]:
AX = np.dot(A, X_ls)
print "AX:\n", AX

AX:
[[ 88.25 ]
 [ 67.625]
 [ 53.125]
 [ 35.125]
 [ 20.625]]


交截圖與程式碼。
file: "ex for OMPISTA (student).doc"
OMP only

In [29]:
np.linalg.lstsq(A, b)#, rcond = None)

(matrix([[ 35.125],
         [ 32.5  ],
         [ 20.625]]),
 matrix([[ 1.375]]),
 3,
 array([ 2.5243378 ,  1.41421356,  0.79228699]))